# Generated by Django 5.0.14 on 2026-02-25 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tradelog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_source', models.CharField(max_length=255)),
                ('key_takeaway', models.TextField()),
                ('application_plan', models.TextField()),
                ('linked_type', models.CharField(choices=[('mistake', 'Mistake'), ('rule', 'Rule'), ('strategy', 'Strategy'), ('none', 'None')], default='none', max_length=20)),
                ('linked_id', models.UUIDField(blank=True, help_text='ID of the related mistake, rule, or strategy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PsychologyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('emotional_state', models.CharField(choices=[('calm', 'Calm'), ('anxious', 'Anxious'), ('fomo', 'FOMO'), ('angry', 'Angry'), ('overconfident', 'Overconfident'), ('uncertain', 'Uncertain')], max_length=20)),
                ('confidence_before', models.IntegerField(help_text='1-10 scale')),
                ('satisfaction_after', models.IntegerField(help_text='1-10 scale')),
                ('pressure_source', models.CharField(blank=True, choices=[('money', 'Money'), ('time', 'Time'), ('missed_move', 'Missed Move'), ('anger', 'Anger'), ('uncertainty', 'Uncertainty')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psych_logs', to='tradelog.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychology_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psychology_logs',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recap_date', models.DateField()),
                ('session_state', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('outcome', models.CharField(choices=[('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad')], max_length=10)),
                ('what_went_right', models.JSONField(blank=True, default=list)),
                ('what_slipped', models.JSONField(blank=True, default=list)),
                ('rule_to_focus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_recaps',
                'ordering': ['-recap_date'],
            },
        ),
        migrations.CreateModel(
            name='TradeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tradelog.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_date', models.DateField()),
                ('session_state', models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10, null=True)),
                ('prompt_text', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('intention_next_session', models.TextField(blank=True)),
                ('limits_followed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('mostly', 'Mostly'), ('no', 'No')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_journals',
                'ordering': ['-journal_date'],
                'unique_together': {('user', 'journal_date')},
            },
        ),
    ]
