# Generated by Django 5.0.14 on 2026-03-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradenote',
            options={'ordering': ['-trade_date', '-trade_time']},
        ),
        migrations.RemoveField(
            model_name='learningnote',
            name='linked_id',
        ),
        migrations.RemoveField(
            model_name='learningnote',
            name='linked_type',
        ),
        migrations.RemoveField(
            model_name='tradenote',
            name='note_text',
        ),
        migrations.RemoveField(
            model_name='tradenote',
            name='trade',
        ),
        migrations.AddField(
            model_name='tradenote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tradenote',
            name='pnl_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradenote',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tradenote',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradenote',
            name='trade_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradenote',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10, null=True),
        ),
    ]
