# Generated by Django 5.0.14 on 2026-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_tradenote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningnote',
            name='linked_type',
            field=models.CharField(choices=[('mistake', 'Mistake'), ('rule', 'Rule'), ('strategy', 'Strategy')], default='strategy', max_length=10),
        ),
    ]
