# Generated by Django 5.0.14 on 2026-04-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_learningnote_linked_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyjournal',
            unique_together=set(),
        ),
    ]
