# Generated by Django 5.0.14 on 2026-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('biannual', '6 Months'), ('annual', 'Annual')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_key',
            field=models.CharField(blank=True, default='', help_text='CMS PricingPlan card_key', max_length=30),
        ),
    ]
