services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5635:5432"

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "5010:80"
      - "2526:25"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:13025
    volumes:
      - .:/app
    ports:
      - "13025:13025"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
    depends_on:
      - db
      - smtp4dev

volumes:
  postgres_data: