# Generated by Django 5.0.14 on 2026-02-25 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('market_types', models.JSONField(blank=True, default=list, help_text='Indian Stocks / Forex / Crypto / Options')),
                ('trade_type', models.CharField(blank=True, choices=[('intraday', 'Intraday'), ('swing', 'Swing'), ('positional', 'Positional')], max_length=15, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('maturity_status', models.CharField(choices=[('testing', 'Testing'), ('developing', 'Developing'), ('mature', 'Mature')], default='testing', max_length=15)),
                ('sample_size_threshold', models.IntegerField(default=30)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to='admin_panel.admin')),
                ('source_strategy', models.ForeignKey(blank=True, help_text='If copied from community, points to original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='strategies.strategy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
