# Generated by Django 5.0.14 on 2026-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='entry_rules',
            field=models.JSONField(blank=True, default=list, help_text='List of entry rules'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='exit_rules',
            field=models.JSONField(blank=True, default=list, help_text='List of exit rules'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='risk_management_rules',
            field=models.JSONField(blank=True, default=list, help_text='List of risk management rules'),
        ),
    ]
