# Generated by Django 5.0.14 on 2026-02-25 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('access_level', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=15)),
                ('profile_picture_url', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to='admin_panel.admin')),
            ],
            options={
                'db_table': 'admins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text='create / edit / delete', max_length=20)),
                ('action_detail', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_performed', to='admin_panel.admin')),
                ('target_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to='admin_panel.admin')),
            ],
            options={
                'db_table': 'admin_admin_actions',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminUserAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_user_id', models.UUIDField()),
                ('action_type', models.CharField(help_text='toggle_active / delete / view_mistakes / view_profile', max_length=50)),
                ('action_detail', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='admin_panel.admin')),
            ],
            options={
                'db_table': 'admin_user_actions',
                'ordering': ['-performed_at'],
            },
        ),
    ]
