# Generated by Django 5.0.14 on 2026-04-24 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_pricingplan_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional short description shown under the title', max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_learning_modules',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order within the module')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='admin_panel.learningmodule')),
            ],
            options={
                'db_table': 'cms_learning_topics',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
