# Generated by Django 5.0.14 on 2026-04-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_learningmodule_learningtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Small badge/label on the card, e.g. "Behavior Control & Prevention"', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='card_key',
            field=models.CharField(choices=[('discipline_tools', 'Discipline Tools (monthly/yearly toggle)'), ('learning_hub', 'Learning Hub (6-month)'), ('combo_monthly', 'Complete System – Monthly Combo'), ('combo_annual', 'Complete System – Annual Combo')], default='discipline_tools', help_text='Fixed identifier that the frontend uses to find this card.', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='cta_label',
            field=models.CharField(blank=True, default='', help_text='Button label, e.g. "Activate Discipline Tools"', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='footer_note',
            field=models.CharField(blank=True, default='', help_text='Small grey text under the button, e.g. "Discipline infrastructure only."', max_length=300),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price — only relevant for discipline_tools card. Leave NULL for others.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short subtitle shown under the heading, e.g. "Traders who want to control activity…"', max_length=300),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='billing_cycle',
            field=models.CharField(choices=[('forever', 'Forever (Free)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', '6 Months'), ('annual', 'Annual')], default='monthly', help_text='Billing cycle label shown on the card.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='features',
            field=models.JSONField(default=list, help_text='Ordered list of feature strings shown as bullet points on the card.'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(help_text='Card heading, e.g. "Discipline Tools"', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Primary price (monthly price for discipline_tools, flat price for others).', max_digits=10),
        ),
    ]
