# Generated by Django 5.0.14 on 2026-02-27 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('tradelog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mistake_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('execution', 'Execution'), ('psychology', 'Psychology'), ('process', 'Process'), ('risk', 'Risk')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('severity_weight', models.IntegerField(help_text='1-10 severity score')),
                ('is_custom', models.BooleanField(default=False)),
                ('is_admin_defined', models.BooleanField(default=False, help_text='Admin mistakes cannot be deleted by users')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mistakes', to='admin_panel.admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mistakes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeMistake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('mistake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_trades', to='mistakes.mistake')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_mistakes', to='tradelog.trade')),
            ],
            options={
                'db_table': 'trade_mistakes',
                'unique_together': {('trade', 'mistake')},
            },
        ),
    ]
