# Generated by Django 5.0.14 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistake',
            name='mistake_mode',
            field=models.CharField(blank=True, choices=[('overtrading', 'Overtrading'), ('revenge_trading', 'Revenge Trading'), ('fomo', 'FOMO'), ('early_exit', 'Early Exit'), ('ignored_stop_loss', 'Ignored Stop Loss'), ('late_exit', 'Late Exit'), ('no_plan', 'No Plan'), ('oversized_position', 'Oversized Position')], help_text='Behavioural pattern this mistake falls under', max_length=30, null=True),
        ),
    ]
