# Generated by Django 5.0.14 on 2026-02-25 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_date', models.DateField()),
                ('trade_time', models.TimeField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=100)),
                ('market_type', models.CharField(choices=[('indian_stocks', 'Indian Stocks'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('options', 'Options')], max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('leverage', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('entry_confidence', models.IntegerField(blank=True, help_text='1-10', null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='1-10', null=True)),
                ('emotional_state', models.CharField(blank=True, choices=[('calm', 'Calm'), ('anxious', 'Anxious'), ('confident', 'Confident'), ('fearful', 'Fearful'), ('fomo', 'FOMO'), ('angry', 'Angry'), ('overconfident', 'Overconfident'), ('uncertain', 'Uncertain')], max_length=20, null=True)),
                ('violation_modes', models.JSONField(blank=True, default=list)),
                ('lessons_learned', models.TextField(blank=True)),
                ('rules_followed', models.JSONField(blank=True, default=list)),
                ('is_disciplined', models.BooleanField(default=True)),
                ('is_tagged_complete', models.BooleanField(default=False, help_text='True when strategy+psychology fully tagged')),
                ('screenshot_urls', models.JSONField(blank=True, default=list)),
                ('import_source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import')], default='manual', max_length=15)),
                ('broker_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='discipline.disciplinesession')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-trade_date', '-trade_time'],
                'indexes': [models.Index(fields=['user', 'trade_date'], name='trades_user_id_9518dd_idx'), models.Index(fields=['user', 'session'], name='trades_user_id_e1227d_idx')],
            },
        ),
    ]
