# Generated by Django 5.0.14 on 2026-02-17 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('indian_stocks', 'Indian Stocks'), ('forex', 'Forex'), ('crypto', 'Crypto')], max_length=20)),
                ('symbol', models.CharField(max_length=50)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('leverage', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('strategy', models.CharField(max_length=100)),
                ('trade_analysis', models.CharField(max_length=150)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('entry_confidence', models.IntegerField(default=5, help_text='1-10 scale')),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='1-10 scale', null=True)),
                ('emotional_state', models.CharField(choices=[('calm', 'Calm'), ('anxious', 'Anxious'), ('fomo', 'FOMO'), ('angry', 'Angry'), ('overconfident', 'Overconfident'), ('uncertain', 'Uncertain')], max_length=50)),
                ('violation_modes', models.JSONField(blank=True, default=list)),
                ('lessons_learned', models.TextField(blank=True)),
                ('rules_followed', models.JSONField(blank=True, default=list)),
                ('is_disciplined', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-entry_date'],
            },
        ),
    ]
