# Generated by Django 5.0.14 on 2026-02-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=15),
            preserve_default=False,
        ),
    ]
