# Generated by Django 5.0.14 on 2026-04-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='market_type',
            field=models.CharField(choices=[('indian_market', 'Indian Market'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('options', 'Options')], max_length=20),
        ),
    ]
