# Generated by Django 5.0.14 on 2026-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0002_alter_trade_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
