# Generated by Django 5.0.14 on 2026-03-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0002_alter_trade_exit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
