# Generated by Django 5.0.14 on 2026-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0003_trade_entry_time_trade_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='outcome_summary',
            field=models.CharField(blank=True, choices=[('target_hit', 'Target Hit'), ('stop_loss_hit', 'Stop Loss Hit'), ('breakeven', 'Breakeven'), ('partial_exit', 'Partial Exit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_analysis',
            field=models.TextField(blank=True, help_text='Why did you take this trade? What was your analysis?'),
        ),
    ]
