# Generated by Django 5.0.14 on 2026-02-28 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('di_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vmi_level', models.CharField(blank=True, max_length=10, null=True)),
                ('drt_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tpr_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fie_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ovr_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('eci_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cas_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dae_r', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('smi_status', models.CharField(blank=True, max_length=15, null=True)),
                ('ddr_level', models.CharField(blank=True, max_length=10, null=True)),
                ('cpi_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_metric_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
