# Generated by Django 5.0.14 on 2026-02-25 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('session_state', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('rules_violated', models.JSONField(blank=True, default=list)),
                ('violations_count', models.IntegerField(default=0)),
                ('hard_violations', models.IntegerField(default=0)),
                ('soft_violations', models.IntegerField(default=0)),
                ('required_actions_completed', models.BooleanField(default=False)),
                ('cooldown_ends_at', models.DateTimeField(blank=True, null=True)),
                ('journal_completed', models.BooleanField(default=False)),
                ('trade_review_completed', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discipline_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='ViolationsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], max_length=10)),
                ('session_state_after', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('violated_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='rules.rule')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_logs', to='discipline.disciplinesession')),
            ],
            options={
                'db_table': 'violations_log',
                'ordering': ['-violated_at'],
            },
        ),
    ]
