# Generated by Django 5.0.14 on 2026-03-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinesession',
            name='peak_state',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', help_text='Highest severity state reached this day — never downgraded on unlock', max_length=10),
        ),
    ]
