# Generated by Django 5.0.14 on 2026-02-25 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('risk', 'Risk'), ('process', 'Process'), ('psychology', 'Psychology'), ('time', 'Time'), ('other', 'Other')], max_length=20)),
                ('rule_type', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], max_length=10)),
                ('trigger_scope', models.CharField(choices=[('per_day', 'Per Day'), ('per_trade', 'Per Trade'), ('post_trigger', 'Post Trigger')], max_length=20)),
                ('trigger_condition', models.JSONField(default=dict, help_text='e.g. {"maxLoss": 5000, "maxDailyPercent": 3}')),
                ('action', models.CharField(choices=[('lock', 'Lock'), ('warn', 'Warn'), ('require_journal', 'Require Journal'), ('restrict_import', 'Restrict Import')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin_defined', models.BooleanField(default=False, help_text='Admin rules cannot be deleted by users')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to='admin_panel.admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
