# Generated by Django 5.0.14 on 2026-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('lock', 'Lock'), ('warn', 'Warn'), ('require_journal', 'Require Journal')], max_length=20),
        ),
    ]
