# Generated by Django 5.0.14 on 2026-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rule_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_system_rule',
            field=models.BooleanField(default=False, help_text='System rules are seeded per-user on registration. Users can update thresholds and toggle is_active, but cannot delete them.'),
        ),
    ]
