# Generated by Django 5.0.14 on 2026-04-10 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_rule_is_system_rule'),
        ('tradelog', '0003_trade_entry_time_trade_exit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_trades', to='rules.rule')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_rules', to='tradelog.trade')),
            ],
            options={
                'db_table': 'trade_rules',
                'unique_together': {('trade', 'rule')},
            },
        ),
    ]
