# Generated by Django 5.0.14 on 2026-04-12 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_rule_triggered', models.BooleanField(default=True)),
                ('notify_rule_violated', models.BooleanField(default=True)),
                ('notify_session_locked', models.BooleanField(default=True)),
                ('notify_session_unlocked', models.BooleanField(default=True)),
                ('auto_delete_after_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
    ]
