# Generated by Django 5.0.14 on 2026-04-13 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_pricingplan_review'),
        ('notifications', '0002_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rule_triggered', 'Rule Triggered'), ('rule_violated', 'Rule Violated'), ('session_locked', 'Session Locked'), ('session_unlocked', 'Session Unlocked'), ('admin_broadcast', 'Admin Broadcast')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipients', models.CharField(choices=[('all', 'All Users'), ('pro', 'Pro'), ('elite', 'Elite'), ('pro_elite', 'Pro & Elite')], default='all', help_text='Which subscription tier(s) receive this broadcast', max_length=20)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='admin_panel.admin')),
            ],
            options={
                'db_table': 'admin_broadcasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
